package com.ihcl.hudiniaggregator.util

object Constants {
    const val CONTENT = "full"
    const val ONLYCHECKREQUESTED = "true"
    const val SOCIAL_MEDIA_FEED_ORDERBYCOLUMN="MentionDateCreated"
    const val SOCIAL_MEDIA_FEED_ORDERBY="desc"
    const val OFFERS ="Offers"
    const val PROMOTIONS ="Promotions"
    const val ROOM_RATES ="Room Rates"
    const val PACKAGES ="Other Packages"
    const val MEMBER_DEAL ="Member Packages"
    const val CLOSED = "Closed"
    const val No_SELL = "No Sell"
    const val SOLD_OUT = "Sold Out"
    const val LIMIT = "Limit"
    const val NO_AVAILABLE_INVENTORY = "NoAvailableInventory"
    const val COUPON_CODE_APPLIED_SUCCESSFULLY = "Coupon Code Applied Successfully"
    const val USED_VALID_COUPON = "Coupon Code is valid and it is already used. Please try with another coupon code"
    const val INVALID_COUPON_CODE = "The coupon code entered is invalid. Please enter a valid coupon code."
    const val REQUIRED_MANDATORY_FIELDS = "Please make sure all the mandatory fields are passed."
    const val NO_COMMON_ROOMS = "The coupon code entered is invalid. Please enter a valid coupon code."
    const val NO_ROOMS_AVAILABLE_FOR_SELECTED_DATES = "SORRY, THERE ARE NO ROOMS AVAILABLE FOR THE SELECTED DATES."
    const val INR = "INR"
    //Check availability request constants
    const val PROMOCODE = "promoCode"
    const val COUPONCODE = "couponCode"
    const val HUDINITOKEN = "HUDINITOKEN"
    const val BEARER = "Bearer"
    const val AUTHORIZATION = "Authorization"
    const val MOBILE = "Mobile"

    //membership level names
    const val TCPG = "TCPG"
    const val TCPS = "TCPS"
    const val TCPP = "TCPP"
    const val TCPC = "TCPC"
    const val CHN = "CHN"
    const val CHG = "CHG"
    const val EC = "EC"
    const val EP = "EP"
    const val EV = "EV"
    const val TATA_DIGITAL_GOLD = "Tata Digital Gold"
    const val TATA_DIGITAL_SILVER = "Tata Digital Silver"
    const val TATA_DIGITAL_PLATINUM = "Tata Digital Platinum"
    const val TATA_DIGITAL_COPPER = "Tata Digital Copper"
    const val CHAMBERS_NATIONAL_MEMBER = "Chambers National Member"
    const val CHAMBERS_GLOBAL_MEMBER = "Chambers Global Member"
    const val EPICURE_CORPORATE = "Epicure Corporate"
    const val EPICURE_PREFERRED = "Epicure Preferred"
    const val EPICURE_PRIVILEGED = "Epicure Privileged"
}