env:
 bookingDevUrl: "http://20.244.61.17:8080/graphql"
 socialMediaUrl: "https://cx-api.locobuzz.com/api/Tickets/InstagramBrandPostList"
 rateAgentPromoUrl: "http://ihcl-hudiniservice:8085/v1/rate-promo-availability"
 sebBookingURL: "https://uatsebappservices.tajhotels.com/api/SEBCRS/SEBBookingRequest"
 hudiniAuthEmail: "tajdev.support@hudini.io"
 hudiniAuthPass: "IHCLHudiniD#2023"
 redisKey: "vzaLORNA7cO9HjIDYg32CTqElV6CzGziDAzCaGRlwCY"
 redisHost: "app-dev-redis.redis.cache.windows.net"
 redisPort: "6380"
 brandName: "tajhotelcorp"
 requestTimeoutMillis : "120000"
 sebUserName : "raju.rathod"
 sebPassword : "Welcome@123"
 sebDomain : "Test"
 chamberRateFilter : "RTG"
 memberTierChambers : "chamber"
